import { Component } from '@angular/core';
import { IonicPage, NavController, NavParams } from 'ionic-angular';
import { Validators, FormBuilder, FormGroup } from '@angular/forms';
import { UserProvider } from '../../providers/user/user';
import { AlertController } from 'ionic-angular';
import { TabsPage } from '../tabs/tabs';

/**
 * Generated class for the LoginPage page.
 *
 * See https://ionicframework.com/docs/components/#navigation for more info on
 * Ionic pages and navigation.
 */

@IonicPage()
@Component({
  selector: 'page-login',
  templateUrl: 'login.html',
})
export class LoginPage {

  public loginForm: FormGroup;

  constructor(
    public navCtrl: NavController,
    public navParams: NavParams,
    private formBuilder: FormBuilder,
    private alertCtrl: AlertController,
    private userProvider: UserProvider,
  ) {
    this.loginForm = this.formBuilder.group({
      // TODO - Add helper when required is not met.
      username: ['', [
        Validators.required,
        Validators.minLength(4),
        Validators.maxLength(20)
        ]
      ],
      password: ['', [
          Validators.required,
          Validators.minLength(7),
          Validators.maxLength(20)
        ]
      ]
    });
  }

  ionViewDidLoad() {
    //console.log('ionViewDidLoad LoginPage');
  }

  /**
    * Displays an alert based on the error's message.
    * @param {any} errmess JSON with error generated by the API.
    */
  loginErrorHandler(errmess: any) {
    // TODO Delete logs
    console.log("eroor");
    console.log(errmess);
    let registerErrorAlert = this.alertCtrl.create({
      title: 'Ups...',
      subTitle: errmess.message,
      buttons: ['Dismiss']
    });
    registerErrorAlert.present();
  }

  /**
   * Sends the field's information to validate in the API.
   */
  onSubmit():void {
    console.log(this.loginForm.value);
    let userCredentials = this.loginForm.value;
    this.userProvider.loginUser(userCredentials)
    .subscribe((resp) => {
      let registerSuccessAlert = this.alertCtrl.create({
        title: 'Yay!',
        subTitle: 'Login succesfull.',
        buttons: ['Dismiss']
      });
      // TODO - Verify save data... Maybe this function not should here
      // this.userProvider.setCurrentLogedInUsername(userCredentials.username);
      registerSuccessAlert.present();
      this.navCtrl.setRoot(TabsPage);
    },
    errmess => this.loginErrorHandler(errmess) );
  }

}
