import { Component } from '@angular/core';
import { IonicPage, NavController, NavParams } from 'ionic-angular';
import { Activity } from '../../shared/activity';
import { ActivityProvider } from '../../providers/activity/activity';
import { AlertController } from 'ionic-angular';
/**
 * Generated class for the ActivityDetailPage page.
 *
 * See https://ionicframework.com/docs/components/#navigation for more info on
 * Ionic pages and navigation.
 */

@IonicPage()
@Component({
  selector: 'page-activity-detail',
  templateUrl: 'activity-detail.html',
})
export class ActivityDetailPage {
  
  private activity : Activity ;
  /**
    * Displays an alert based on the error's message.
    * @param {any} errmess JSON with error generated by the API.
    */
  getActivityErrorHandler(errmess: any): void {
    let registerErrorAlert = this.alertCtrl.create({
      title: 'Ups...',
      subTitle: errmess.message,
      buttons: ['Dismiss']
    });
    registerErrorAlert.present();
  }

  constructor(
    public navCtrl: NavController,
    public navParams: NavParams,
    public activityProvider : ActivityProvider,
    private alertCtrl: AlertController,
  ) {  }

  ionViewDidLoad() {
    this.activity.name = 'Dummy'; // Dummy Line to remove warning
    this.loadActivity();  
  }

  /**
   * Loads the activity that comes as a parameter. It takes
   * the ID and fetches it from the DB. 
   */
  loadActivity():void {
    const activityId = this.navParams.get('activityId');
    this.activityProvider.getActivityById(activityId)
      .subscribe((resp) => {
        let activityRes = JSON.stringify(resp);
        this.activity = <Activity>JSON.parse(activityRes);
      }
      , errmess => this.getActivityErrorHandler(errmess));
  }

  onSuscribe() {
    const alert = this.alertCtrl.create({
      title: 'Subscription Success',
      subTitle: 'Thanks for subscribe!',
      buttons: ['OK']
    });
    alert.present();
    
  }

}
