import { Component } from '@angular/core';
import { IonicPage, NavController, NavParams, ToastController, AlertController, ActionSheetController } from 'ionic-angular';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Activity } from '../../shared/activity';
import { ActivityProvider } from '../../providers/activity/activity';
import { Camera, CameraOptions } from '@ionic-native/camera';

/**
 * Generated class for the CreateActivityPage page.
 *
 * See https://ionicframework.com/docs/components/#navigation for more info on
 * Ionic pages and navigation.
 */

@IonicPage()
@Component({
  selector: 'page-create-activity',
  templateUrl: 'create-activity.html',
})
export class CreateActivityPage {

  createActivityForm: FormGroup;

  constructor(
    public navCtrl: NavController,
    public navParams: NavParams,
    private activityProvider: ActivityProvider,
    private toastCtrl: ToastController,
    private alertCtrl: AlertController,
    private camera: Camera,
    private actionSheetCtrl: ActionSheetController,
    private formBuilder: FormBuilder, ) {
    this.buildForm();
  }

  ionViewDidLoad() {
    console.log('ionViewDidLoad CreateActivityPage');
  }

  /**
   * Opens the camera to add a picture. Sets the camara 
   * quality and gets the picture in base64.
   */
  openCamara() {
    const options: CameraOptions = {
      quality: 100,
      destinationType: this.camera.DestinationType.FILE_URI,
      encodingType: this.camera.EncodingType.JPEG,
      mediaType: this.camera.MediaType.PICTURE
    }

    this.camera.getPicture(options).then((imageData) => {
      // imageData is either a base64 encoded string or a file URI
      // If it's base64 (DATA_URL):
      let base64Image = 'data:image/jpeg;base64,' + imageData;
    }, (err) => {
      // Handle error
    });
  }

  /**
   * Opens the galery to add a picture. Sets the picture 
   * quality and gets the picture in base64.
   */
  openGalery() {
    const options: CameraOptions = {
      quality: 100,
      destinationType: this.camera.DestinationType.FILE_URI,
      encodingType: this.camera.EncodingType.JPEG,
      mediaType: this.camera.MediaType.PICTURE,
      sourceType: this.camera.PictureSourceType.PHOTOLIBRARY
    }

    this.camera.getPicture(options).then((imageData) => {
      // imageData is either a base64 encoded string or a file URI
      // If it's base64 (DATA_URL):
      let base64Image = 'data:image/jpeg;base64,' + imageData;
    }, (err) => {
      // Handle error
    });
  }

  /**
   * Creates a new activiy and stores it in the data base.
   */
  postActivity() {
    let newActivity = this.createActivityForm.value;
    newActivity.begin_date = this.formatDate(new Date(this.createActivityForm.value.begin_date + ' ' + this.createActivityForm.value.begin_time));
    newActivity.end_date = this.formatDate(new Date(this.createActivityForm.value.end_date + ' ' + this.createActivityForm.value.end_time));
    delete newActivity.begin_time;
    delete newActivity.end_time;
    this.activityProvider.postActivity(newActivity).subscribe((resp) => {
      this.presentToast();
      this.createActivityForm.reset();
      
    }, errmess => this.postActivitiesErrorHandler(errmess));
  }

  /**
   * Builds the form and adds it's validators.
   */
  private buildForm(): void {
    this.createActivityForm = this.formBuilder.group({
      name: ['',
        [
          Validators.required, Validators.minLength(5), Validators.maxLength(20)
        ]
      ],
      description: ['',
        [
          Validators.required, Validators.minLength(5), Validators.maxLength(20)
        ]
      ],
      location: ['Javeriana',
        [
          Validators.required, Validators.minLength(5), Validators.maxLength(20)
        ]
      ],
      begin_date: ['', [Validators.required]],
      begin_time: ['', [Validators.required]],
      end_date: ['', [Validators.required]],
      end_time: ['', [Validators.required]],
      max_participants: ['',
        [
          Validators.required, Validators.min(1), Validators.max(100)
        ]
      ]
    });
  }

  presentToast(): void {
    const toast = this.toastCtrl.create({
      message: 'Yay!, Activity Created',
      duration: 3000,
      position: 'top'
    });
    toast.present();
  }

  /**
   * Displays an alert based on the error's message.
   * @param {any} errmess JSON with error generated by the API.
   */
  postActivitiesErrorHandler(errmess): void {
    const registerErrorAlert = this.alertCtrl.create(
      { title: 'Ups...', subTitle: errmess.error, buttons: ['Dismiss'] });
    registerErrorAlert.present();
  }

  private formatDate(date: Date) {
    let utc = (date.getTimezoneOffset() * -1) / 60;
    utc *= 100;
    let utcSign = '+' ;
    if( utc < 0 ) {
        utcSign = '-';
        utc*=-1;
    }
    const dateFormated: string = 
          date.getFullYear() 
          + '-' + (date.getMonth() + 1) 
          + '-' + date.getDate() 
          + 'T' + date.getHours() 
          + ':' + date.getMinutes()
          + utcSign
          + '0' + utc;
    return dateFormated;
  }

  /**
   * Displays the options for image to be uploaded.
   */
  presentActionSheet() {
    const actionSheet = this.actionSheetCtrl.create({
      title: 'Upload Photo',
      buttons: [
        {
          text: 'Delete',
          role: 'destructive',
          handler: () => { console.log('Destructive clicked'); }
        }, {
          text: 'Take Picture',
          icon: 'icon-camera',
          handler: () => { console.log('Take Picture clicked'); }
        }, {
          text: 'Upload From Library',
          icon: 'icon-images',
          handler: () => { console.log('Upload clicked'); }
        }, {
          text: 'Cancel',
          role: 'cancel',
          handler: () => { console.log('Cancel clicked'); }
        }
      ]
    });
    actionSheet.present();
  }

}
